import os #limpar prompt
import time #espera

os.system("cls")

#     [id,  tipo, palavra, continente, pais, dificuldade]

palavra = [
    [1, 'país', 'Brasil', 'América do Sul', None, 'facil'],
    [2, 'país', 'Canadá', 'América do Norte', None, 'facil'],
    [3, 'país', 'Madagascar', 'África', None, 'medio'],
    [4, 'país', 'Cazaquistão', 'Ásia', None, 'dificil'],
    [5, 'país', 'Islândia', 'Europa', None, 'medio'],
    [6, 'país', 'Quirguistão', 'Ásia', None, 'dificil'],
    [7, 'país', 'Butão', 'Ásia', None, 'medio'],
    [8, 'país', 'Liechtenstein', 'Europa', None, 'dificil'],
    [9, 'país', 'Croácia', 'Europa', None, 'medio'],
    [10, 'país', 'Uruguai', 'América do Sul', None, 'facil'],
    [11, 'país', 'Egito', 'África', None, 'facil'],
    [12, 'país', 'Chade', 'África', None, 'facil'],
    [13, 'país', 'Eslováquia', 'Europa', None, 'dificil'],
    [14, 'país', 'Togo', 'África', None, 'facil'],
    [15, 'país', 'Zâmbia', 'África', None, 'medio'],
    [16, 'estado', 'Alasca', 'América do Norte', 'Estados Unidos', 'medio'],
    [17, 'estado', 'Tasmânia', 'Oceania', 'Austrália', 'dificil'],
    [18, 'estado', 'Quebec', 'América do Norte', 'Canadá', 'medio'],
    [19, 'estado', 'Andaluzia', 'Europa', 'Espanha', 'dificil'],
    [20, 'estado', 'Baviera', 'Europa', 'Alemanha', 'medio'],
    [21, 'estado', 'Califórnia', 'América do Norte', 'Estados Unidos', 'facil'],
    [22, 'estado', 'Punjab', 'Ásia', 'Índia', 'medio'],
    [23, 'estado', 'Galícia', 'Europa', 'Espanha', 'dificil'],
    [24, 'estado', 'Guarani', 'América do Sul', 'Brasil', 'medio'],
    [25, 'estado', 'Hokkaido', 'Ásia', 'Japão', 'dificil'],
    [26, 'cidade', 'Tóquio', 'Ásia', 'Japão', 'facil'],
    [27, 'cidade', 'Nairobi', 'África', 'Quênia', 'medio'],
    [28, 'cidade', 'Zurique', 'Europa', 'Suíça', 'medio'],
    [29, 'cidade', 'Recife', 'América do Sul', 'Brasil', 'facil'],
    [30, 'cidade', 'Edimburgo', 'Europa', 'Reino Unido', 'dificil'],
    [31, 'cidade', 'Valparaíso', 'América do Sul', 'Chile', 'medio'],
    [32, 'cidade', 'Istambul', 'Europa/Ásia', 'Turquia', 'medio'],
    [33, 'cidade', 'Ljubljana', 'Europa', 'Eslovênia', 'dificil'],
    [34, 'cidade', 'Córdoba', 'América do Sul', 'Argentina', 'medio'],
    [35, 'cidade', 'Bruges', 'Europa', 'Bélgica', 'dificil'],
    [36, 'cidade', 'Cracóvia', 'Europa', 'Polônia', 'medio'],
    [37, 'cidade', 'Arequipa', 'América do Sul', 'Peru', 'medio'],
    [38, 'cidade', 'Manágua', 'América Central', 'Nicarágua', 'medio'],
    [39, 'cidade', 'Chiang Mai', 'Ásia', 'Tailândia', 'medio'],
    [40, 'cidade', 'Xangai', 'Ásia', 'China', 'facil'],
    [41, 'cidade', 'Osasco', 'América do Sul', 'Brasil', 'facil'],
    [42, 'cidade', 'Mendoza', 'América do Sul', 'Argentina', 'medio'],
    [43, 'cidade', 'Helsinque', 'Europa', 'Finlândia', 'medio'],
    [44, 'cidade', 'Gênova', 'Europa', 'Itália', 'medio'],
    [45, 'cidade', 'Cusco', 'América do Sul', 'Peru', 'medio'],
    [46, 'cidade', 'Cusco', 'América do Sul', 'Peru', 'medio'],
    [47, 'estado', 'Galícia', 'Europa', 'Espanha', 'dificil'],
    [48, 'país', 'Liechtenstein', 'Europa', None, 'dificil'],
    [49, 'estado', 'Baviera', 'Europa', 'Alemanha', 'medio'],
    [50, 'país', 'Zâmbia', 'África', None, 'medio'],
    [51, 'país', 'Liechtenstein', 'Europa', None, 'dificil'],
    [52, 'cidade', 'Tóquio', 'Ásia', 'Japão', 'facil'],
    [53, 'cidade', 'Ljubljana', 'Europa', 'Eslovênia', 'dificil'],
    [54, 'cidade', 'Recife', 'América do Sul', 'Brasil', 'facil'],
    [55, 'cidade', 'Bruges', 'Europa', 'Bélgica', 'dificil'],
    [56, 'país', 'Eslováquia', 'Europa', None, 'dificil'],
    [57, 'estado', 'Hokkaido', 'Ásia', 'Japão', 'dificil'],
    [58, 'estado', 'Alasca', 'América do Norte', 'Estados Unidos', 'medio'],
    [59, 'cidade', 'Xangai', 'Ásia', 'China', 'facil'],
    [60, 'estado', 'Tasmânia', 'Oceania', 'Austrália', 'dificil'],
    [61, 'estado', 'Quebec', 'América do Norte', 'Canadá', 'medio'],
    [62, 'país', 'Madagascar', 'África', None, 'medio'],
    [63, 'estado', 'Galícia', 'Europa', 'Espanha', 'dificil'],
    [64, 'país', 'Butão', 'Ásia', None, 'medio'],
    [65, 'cidade', 'Istambul', 'Europa/Ásia', 'Turquia', 'medio'],
    [66, 'estado', 'Hokkaido', 'Ásia', 'Japão', 'dificil'],
    [67, 'cidade', 'Manágua', 'América Central', 'Nicarágua', 'medio'],
    [68, 'país', 'Brasil', 'América do Sul', None, 'facil'],
    [69, 'país', 'Canadá', 'América do Norte', None, 'facil'],
    [70, 'país', 'Madagascar', 'África', None, 'medio'],
    [71, 'país', 'Liechtenstein', 'Europa', None, 'dificil'],
    [72, 'estado', 'Alasca', 'América do Norte', 'Estados Unidos', 'medio'],
    [73, 'estado', 'Andaluzia', 'Europa', 'Espanha', 'dificil'],
    [74, 'estado', 'Califórnia', 'América do Norte', 'Estados Unidos', 'facil'],
    [75, 'país', 'Liechtenstein', 'Europa', None, 'dificil'],
    [76, 'estado', 'Quebec', 'América do Norte', 'Canadá', 'medio'],
    [77, 'cidade', 'Cusco', 'América do Sul', 'Peru', 'medio'],
    [78, 'estado', 'Punjab', 'Ásia', 'Índia', 'medio'],
    [79, 'país', 'Croácia', 'Europa', None, 'medio'],
    [80, 'país', 'Islândia', 'Europa', None, 'medio'],
    [81, 'país', 'Quirguistão', 'Ásia', None, 'dificil'],
    [82, 'cidade', 'Cracóvia', 'Europa', 'Polônia', 'medio'],
    [83, 'cidade', 'Cusco', 'América do Sul', 'Peru', 'medio'],
    [84, 'cidade', 'Osasco', 'América do Sul', 'Brasil', 'facil'],
    [85, 'cidade', 'Gênova', 'Europa', 'Itália', 'medio'],
    [86, 'cidade', 'Helsinque', 'Europa', 'Finlândia', 'medio'],
    [87, 'país', 'Madagascar', 'África', None, 'medio'],
    [88, 'país', 'Islândia', 'Europa', None, 'medio'],
    [89, 'estado', 'Galícia', 'Europa', 'Espanha', 'dificil'],
    [90, 'país', 'Canadá', 'América do Norte', None, 'facil'],
    [91, 'cidade', 'Recife', 'América do Sul', 'Brasil', 'facil'],
    [92, 'cidade', 'Chiang Mai', 'Ásia', 'Tailândia', 'medio'],
    [93, 'estado', 'Quebec', 'América do Norte', 'Canadá', 'medio'],
    [94, 'cidade', 'Ljubljana', 'Europa', 'Eslovênia', 'dificil'],
    [95, 'cidade', 'Cracóvia', 'Europa', 'Polônia', 'medio'],
    [96, 'estado', 'Califórnia', 'América do Norte', 'Estados Unidos', 'facil'],
    [97, 'país', 'Canadá', 'América do Norte', None, 'facil'],
    [98, 'estado', 'Quebec', 'América do Norte', 'Canadá', 'medio'],
    [99, 'estado', 'Galícia', 'Europa', 'Espanha', 'dificil'],
    [100, 'cidade', 'Xangai', 'Ásia', 'China', 'facil'],
    [101, 'cidade', 'Helsinque', 'Europa', 'Finlândia', 'medio'],
    [102, 'cidade', 'Cusco', 'América do Sul', 'Peru', 'medio'],
    [103, 'país', 'Islândia', 'Europa', None, 'medio'],
    [104, 'estado', 'Tasmânia', 'Oceania', 'Austrália', 'dificil'],
    [105, 'país', 'Islândia', 'Europa', None, 'medio'],
    [106, 'estado', 'Andaluzia', 'Europa', 'Espanha', 'dificil'],
    [107, 'estado', 'Galícia', 'Europa', 'Espanha', 'dificil'],
    [108, 'cidade', 'Ljubljana', 'Europa', 'Eslovênia', 'dificil'],
    [109, 'cidade', 'Edimburgo', 'Europa', 'Reino Unido', 'dificil'],
    [110, 'país', 'Cazaquistão', 'Ásia', None, 'dificil'],
]

